Add name, race and ai as properties for ExampleBot
Fixes these when launching a ladder manager game:

AttributeError: 'ExampleBot' object has no attribute 'ai'
AttributeError: 'ExampleBot' object has no attribute 'name'
AttributeError: 'ExampleBot' object has no attribute 'race'

I am not sure why these are not required by the sc2.BotAI constructor though.